name: verl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.0
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - astor==0.8.1
      - attrs==25.4.0
      - av==16.0.1
      - backoff==2.2.1
      - blake3==1.0.8
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - codetiming==1.4.0
      - colorful==0.5.8
      - compressed-tensors==0.9.2
      - cupy-cuda12x==13.6.0
      - datasets==4.4.1
      - deprecated==1.3.1
      - depyf==0.18.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.124.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flash-attn==2.7.4.post1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-metadata==6.11.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - json5==0.12.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - math-verify==0.8.0
      - mathruler==0.1.0
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nanobind==2.10.2
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - ninja==1.13.0
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==2.11.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-exporter-otlp-proto-http==1.39.1
      - opentelemetry-exporter-prometheus==0.40b0
      - opentelemetry-instrumentation==0.44b0
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opentelemetry-semantic-conventions-ai==0.4.13
      - orjson==3.11.5
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - peft==0.18.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pylatexenc==2.10
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.43.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scipy==1.16.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.10.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.2.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - verl==0.2.0.dev0
      - virtualenv==20.35.4
      - vllm==0.8.3
      - wandb==0.23.1
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - xformers==0.0.29.post2
      - xgrammar==0.1.17
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /users/PAS1576/hsaest/miniconda3/envs/verl
